//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.DonHangChiTiets = new HashSet<DonHangChiTiet>();
        }
    
        public int MaDonHang { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public Nullable<System.DateTime> ThoiGianDatHang { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string TrangThai { get; set; }
        public string LoaiYeuCau { get; set; }
        public Nullable<System.DateTime> NgayGioTrangThai { get; set; }
        public Nullable<byte> DanhGia { get; set; }
        public string DiaChiGiao { get; set; }
        public Nullable<System.DateTime> ThoiGianGiao { get; set; }
        public Nullable<int> ShopId { get; set; }
        public string ShopName { get; set; }
        public string ShopPhone { get; set; }
        public Nullable<bool> SynchronizedUser { get; set; }
        public Nullable<bool> SynchronizedShop { get; set; }
        public Nullable<bool> SyncPostMan { get; set; }
        public Nullable<int> PostMan { get; set; }
    
        public virtual ICollection<DonHangChiTiet> DonHangChiTiets { get; set; }
    }
}
